### ISSUE TITLE
Zen 3 VSOC LLC?

### ISSUE THREAD

**Issue by the4anoni** [integralfx/MemTestHelper#49]
Hi
This guide doesn't mention anything about SoC Loadline Level Calibration, especially on Zen3. I'm newbie to overclocking, what it actually does, does it matter and should I touch this or just leave on auto?

**Comment by integralfx** [comment]
LLC controls how much voltage droop (Vdroop) there is when under load. You might notice that when you stress test your RAM, your SoC voltage is a bit below what you set. LLC can counteract this with some caveats (have a look at some of buildzoid's videos explaining LLC).

Since the SoC doesn't draw much current, it's fine to have LLC higher (less Vdroop) than you would on the CPU. It can help with stability but if you don't have any issues then it's fine to leave it on auto.
